### ISSUE TITLE
本地模型的路径出现问题

### ISSUE THREAD

**Issue by leeeex** [the-seeds/imitater#5]
我的.env文件声明
AGENT_TYPE=react

CHAT_MODEL_PATH=/mnt/workspace/qwen-1_8b-agent
CHAT_MODEL_DEVICE=0
CHAT_TEMPLATE_PATH=templates/qwen.jinja
GENERATION_CONFIG_PATH=generation_config/qwen

EMBED_MODEL_PATH=/mnt/workspace/bge-small-zh-v1
EMBED_MODEL_DEVICE=1
EMBED_BATCH_SIZE=16

SERVICE_PORT=8010

# tests
OPENAI_BASE_URL=http://192.168.0.1:8010/v1
OPENAI_API_KEY=0

报错：
2024-02-01 17:15:56,578 - modelscope - ERROR - Authentication token does not exist, failed to access model /mnt/workspace/qwen-1_8b-agent which may not exist or may be                 private. Please login first.
Traceback (most recent call last):
  File "/opt/conda/envs/imitater/lib/python3.10/site-packages/modelscope/hub/errors.py", line 91, in handle_http_response
    response.raise_for_status()
  File "/opt/conda/envs/imitater/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.modelscope.cn/api/v1/models//mnt/workspace/qwen-1_8b-agent/revisions?EndTime=1706778956

环境是阿里云的DSW，好像不认我配置的路径，依然是取魔搭下载模型

**Comment by hiyouga** [comment]
镜像的问题
